# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: ANTONY KIRAN KOLARIKKAL DAVID
title: |
  BS-MS Student, Indian Institute of Science Education and Research (IISER) Pune
email: antonykiran10@gmail.com

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: _antonykiran10
github_username:  antonykiran10
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyllgit pull
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: antonykiran10
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a neuroscientist with interdisciplinary coursework and lab experiences.
  A biologist with experience in Molecular biology and scientific programming exploring ways to harness the powers of molecular biology, imaging and data analysis to better understand how the brain forms its connections.

  <mark>Neurobiology</mark>  <mark>Computational Biology</mark>  <mark>Molecular Biology</mark>

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Neuronal Connectivity Laboratory
        link: https://neuronalconnectivity.wixsite.com/start
        link_text: Link to Website
        sub_title: Master's Thesis Student
        caption: May 2022 - Present
        quote: >
          Visually guided behaviours in Zebrafish larvae and the role of Fmn2b
        description: | # this will include new lines to allow paragraphs
            Designing behavioural assays to study visually guided behaviours in larval zebrafish. Developed a platform to reliably perform restrained larval assays including an automatic stimulus delivery and integration unit and a pipeline for automatic behavioral analysis.
            
            Supervisor: **Dr. Aurnab Ghose**, Division of Biology, IISER Pune

      - layout: left
        title: Neuronal Connectivity Laboratory
        link: https://neuronalconnectivity.wixsite.com/start
        link_text: Link to Website
        sub_title: Semester Project Student
        caption: Jan 2022 - Apr 2022
        quote: >
          Modelling Neurodevelopmental disorders in zebrafish
        description: | # this will include new lines to allow paragraphs
            Characterization of zKPTN protein in Zebrafish neural development by generating conditional knockout of kaptin using CRISPR-Cas9 gene editing system.
            
            Supervisor: **Dr. Aurnab Ghose**, Division of Biology, IISER Pune
      - layout: left
        title: Curem Biotech LLP
        link: https://curembiotech.com/
        link_text: Link to Website
        sub_title: R&D intern
        caption: Aug 2021 - Feb 2022
        quote: >
          In-Silico designing and optimizing Aptamers against bio markers for Plasmodium falciparum malaria
        description: | # this will include new lines to allow paragraphs
            Generating a pipeline for designing and optimizing aptamers (ssDNA/RNA) against different infectious antigen for disease diagnostics using bioinformatic techniques. Involved in the initial phase for the R&D work for finding new leads for the project.
            
            Supervisor: **Dr. Saikrishnan Kayarat**, Division of Biology, IISER Pune

      - layout: left
        title: Computational Neurobiology Laboratory
        link: https://sites.google.com/view/computationalneurobiologylab/home?
        link_text: Link to Website
        sub_title: Semester Project Student
        caption: Aug 2021 - Jan 2022
        quote: >
          Simulate computational models for Astrocyte-Neuron interaction
        description: | # this will include new lines to allow paragraphs
            Replication of a biophysical model for calcium dependent gliotransmitter release at a tripartite synapse which was developed in the lab ([Pillai and Nadkarni, 2022](https://doi.org/10.1371/journal.pcbi.1010334)).
            
            Supervisor: **Dr. Suhita Nadkarni**, Division of Biology, IISER Pune

      - layout: left
        title: Weather, Climate and People
        link: https://joymonteiro.github.io/
        link_text: Link to Website
        sub_title: Summer Intern
        caption: May 2021 - Jun 2021
        quote: >
          BharatSim for compartmentalized epidemiological modelling
        description: | # this will include new lines to allow paragraphs
            A short-term project to learn about epidemiological modelling using BharatSim, a collaborative project between Ashoka University (Haryana, India) and Thoughtworks, funded by the Bill & Melinda Gates Foundation
            
            Supervisor: **Dr. Joy Merwin Monteiro**, Division of Earth, and Climate Science, IISER Pune
      
      - layout: left
        title: iGEM IISER-Pune-India 2020
        link: https://2020.igem.org/Team:IISER-Pune-India
        link_text: Link to Website
        sub_title: Core Team member
        caption: Nov 2019 - Nov 2020
        quote: >
          Anopheles: The Half Blood Princess
        description: | # this will include new lines to allow paragraphs
            Represented IISER Pune at the Giant Jamboree of the iGEM 2020 competition.
            Involved in the conceptualization and research of the project aimed at developing a novel peptide library against malaria and its documentation on the team wiki.
            Was part of the Dry Lab team involved in researching, troubleshooting and
            developing computational models of Novel peptides against Plasmodium falciparum
            malaria. Involved in developing, troubleshooting, and documenting the scripts used on the
            team's GitHub repository
            
            Supervisor: **Dr. Sanjeev Galande**, Division of Biology, IISER Pune (currently on lien to Shiv Nadar University, Uttar Pradesh, India)

      - layout: left
        title: Neuronal Connectivity Laboratory
        link: https://neuronalconnectivity.wixsite.com/start
        link_text: Link to Website
        sub_title: Winter Intern
        caption: Dec 2019 - Feb 2020
        quote: >
          Zebrafish in neuroscience research
        description: | # this will include new lines to allow paragraphs
            A short internship to get familiarized with basic laboratory techniques and zebrafish handling for research purposes
            
            Supervisor: **Dr. Aurnab Ghose**, Division of Biology, IISER Pune
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Indian Institute of Science Education and Research (IISER) Pune
        caption: 2018 - Present
        sub_title: BS-MS Biology
        quote: >
          
          
        description: | # this will include new lines to allow paragraphs
          5-year Integrated Master's Program

          Relevant Coursework:

          - Introductory courses in all basic and applied disciplines of Biology, Chemistry, Physics, Mathematics, Earth and Climate Sciences, Humanities and Computation. During the first two years.
          - Advanced courses in Biochemistry, Developmental Biology, Structural biology, Advanced immunology, Scientific literature Review, Mathematical and Computational Biology Evolution and Biology and Disease during my 4th year
          - A yearlong master's thesis during the 5th year entitled "Visually guided behaviours in Zebrafish larvae and the role of Fmn2b" at the Neuronal Connectivity Laboratory, IISER Pune.
          
          Current CGPA: _

          Current Semester: 10; doing my master's thesis

      - layout: left
        title: Model Technical Higher Secondary School
        caption: Jun 2015 - Mar 2017
        sub_title: Higher Secondary Schooling-Integrated Sciences Stream (Technical)
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Board of Higher Secondary Examinations, Government of Kerala



      - layout: left
        title: St. Philomina's HSS
        caption: Jun 2014 - Mar 2015
        sub_title: Secondary School Leaving Certificate (SSLC)
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          General Education Department, Government of Kerala


  - title: Achievements and Awards
      - layout: left
        title: CSIR-Junior Research Fellowship (CSIR-JRF)
        caption: Mar 2022
        sub_title: AIR 123
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Qualified in the National level entrance examination of Council of Scientific and Industrial Research 
          (CSIR) for the Junior Research Fellowship (JRF) with all India Rank 123 for eligibility for lectureship and funded PhD and projects in Indian Universities.

      - layout: left
        title: 'Graduate Aptitude Test in Engineering (GATE) : Life Science Stream'
        caption: Mar 2022
        sub_title: AIR 1098
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Qualified in the National Level aptitude test in Engineering conducted jointly by the seven Indian Institute of Technology (IIT) and 
          Indian Institute of Science (IISc), Bengaluru with all India Rank 1098 for eligibility into various master's and PhD programs in India and Recruitment into public sector companies.

      - layout: left
        title: Gold Medal at the iGEM competition 2020
        caption: Nov 2020
        # sub_title: AIR 1098
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Represented IISER Pune at the International Genetically Engineered Machines (iGEM) competition, a synthetic biology expo organized by the 
          iGEM foundation, and our team bagged the gold medal for satisfying the prescribed medal criterions.

      - layout: left
        title: iGEMer's Award 2020
        caption: Nov 2020
        # sub_title: AIR 1098
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Represented IISER Pune at the International Genetically Engineered Machines (iGEM) competition, a synthetic biology expo organized by the iGEM foundation and our team's project was voted the best project by all other competing team.


  - title: Conferences and Workshops
      - layout: left
        title: No-Garland Neuroscience 2023 (NGN 2023)
        caption: Feb 2023
        # sub_title: AIR 123
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Attended this 3-day conference on Neuroscience.

      - layout: left
        title: Indian Zebrafish Investigators Meeting 2022 (IZIM 2022)
        caption: Sep 2022
        # sub_title: AIR 123
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Attended this 3-day IZIM 2020 conference and was also part of the organizing committee.

      - layout: left
        title: iGEM Indian Jamboree Meetup 2021
        caption: Nov 2021
        # sub_title: AIR 123
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Attended this 2-day meetup at Goa and celebrated synthetic biology.

      - layout: left
        title: iGEM Giant Jamboree
        caption: Nov 2020
        # sub_title: AIR 123
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Attended and presented the team project and won the gold medal for the project and
          iGEMer's award. The 10-day virtual event was focused on various aspects of synthetic
          biology along with an entrepreneur angle as well.

      - layout: left
        title: All India iGEM meet 2020
        caption: Jul 2020
        # sub_title: AIR 123
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Attended this 2-day virtual meeting and presented our iGEM
          project. 

      - layout: left
        title: Robotics Workshop, IISER Pune
        caption: Oct 2019
        # sub_title: AIR 123
        quote: >          
          
        description: | # this will include new lines to allow paragraphs
          Attended this 2-day workshop and learned the basics on using Arduino microcontroller.
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
